<?php
// $Id$

/**
 * @file
 * Provides the uninstall hook for the Konami Code module.
 */

/**
 * Implementation of hook_uninstall().
 */
function konamicode_uninstall() {
  // Remove all stored settings.
  db_query('DELETE FROM {variable} WHERE name LIKE "konamicode_%"');
}

/**
 * Previous versions just had the redirect plugin.
 */
function konamicode_update_6001() {
  variable_set('konamicode_actions', array('redirect' => 'redirect'));
}
